name: Build and Deploy to Separate Repo

on:
  push:
    branches:
      - main  # Escucha cambios en la rama main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the source repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Necesario para hacer push a otro repositorio

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.9.0'  # Especifica la versión de Node.js 20.9.0

      - name: Install dependencies
        run: npm install  # Cambia esto según tu gestor de paquetes

      - name: Build project
        run: npm run build  # Cambia esto según el script de build de tu proyecto

      - name: Clone target repository
        run: |
          git clone https://github.com/MizzioCoding/Arquitecto2-Builded.git builded-repo
          cd builded-repo
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Copy built files to target repository
        run: |
          rm -rf builded-repo/*
          cp -r dist/* builded-repo/
          
      - name: Commit and push changes to target repository
        run: |
          cd builded-repo
          git add .
          git commit -m "Builded from main branch" || echo "No changes to commit"
          git push origin main || echo "Nothing to push, branch is up to date"
