name: Build and Deploy to Builded
on:
  push:
    branches:
      - main  # Escucha cambios en la rama main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Necesario para hacer push a otra rama

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.9.0'  # Especifica la versión de Node.js

      - name: Install dependencies
        run: npm install  # Cambia esto según tu gestor de paquetes

      - name: Build project
        run: npm run build  # Cambia esto según el script de build de tu proyecto

      - name: Copy .htaccess to dist folder
        run: cp .htaccess dist/.htaccess

      - name: Switch to builded branch
        run: git checkout builded

      - name: Copy built files to builded branch
        run: |
          rm -rf *  # Borra todo el contenido en la rama "builded"
          cp -r ../dist/* .  # Copia los archivos generados en "dist" a la raíz de la rama "builded"

      - name: Commit and push changes to builded branch
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add -A
          git commit -m "Deploy build to builded branch" || echo "No changes to commit"
          git push origin builded || echo "Nothing to push, branch is up to date"
