name: Build and Deploy to Builded

on:
  push:
    branches:
      - main  # Escucha cambios en la rama main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Necesario para hacer push a otra rama

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Especifica la versión de Node.js (si usas Node)

      - name: Install dependencies
        run: npm install  # Cambia esto según tu gestor de paquetes

      - name: Build project
        run: npm run build  # Cambia esto según el script de build de tu proyecto

      - name: Deploy to Builded
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout -b builded
          git add -f dist/  # Asegura que la carpeta generada sea rastreada
          git commit -m "Builded" || echo "No changes to commit"
          git push origin builded || echo "Nothing to push, branch is up to date"

